steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_AUTH_MODE=${_NEXT_PUBLIC_AUTH_MODE}'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/classroom-check-in/web:${SHORT_SHA}'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/classroom-check-in/web:latest'
      - '.'
images:
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/classroom-check-in/web:${SHORT_SHA}'
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/classroom-check-in/web:latest'
substitutions:
  _NEXT_PUBLIC_API_URL: 'https://api-102013220292.asia-northeast1.run.app'
  _NEXT_PUBLIC_AUTH_MODE: 'dev'
